import type {
  CartLine,
  Category,
  DashboardMetric,
  Deal,
  DealItem,
  DeliveryZone,
  Order,
  Product,
  SiteSettings,
} from "@/types/commerce";

export const siteSettings: SiteSettings = {
  id: 1,
  siteName: "Hyderabad Cheese Store",
  tagline: "Premium cheese and frozen food, delivered fast.",
  whatsappNumber: "923001234567",
  logoUrl: "",
  heroKicker: "Premium frozen & dairy",
  heroTitle: "Fresh cheese. Frozen favourites.",
  heroSubtitle: "Luxury essentials for Hyderabad, delivered with speed.",
  homepageStoryTitle: "Curated for everyday indulgence.",
  homepageStoryBody: "Cheese, frozen food, and extras in one polished store.",
  productsSectionTitle: "Best Sellers",
  dealsSectionTitle: "Live Deals",
  contactSectionTitle: "Contact Store",
  announcementBar:
    "Fresh deals weekly. Delivery charges update by area.",
  contactEmail: "hello@hyderabadcheesestore.com",
  contactPhone: "+92 300 1234567",
  address: "Latifabad, Hyderabad, Sindh",
  businessHours: "Daily, 11:00 AM to 11:00 PM",
  primaryColor: "#d7a128",
  secondaryColor: "#111111",
  backgroundColor: "#f4efe5",
  surfaceColor: "#fffaf1",
  currencyCode: "PKR",
};

export const categories: Category[] = [
  {
    id: "cat-frozen",
    slug: "frozen-food",
    name: "Frozen Food",
    description: "Cold favourites, ready fast.",
    imageUrl: null,
    accentTone: "frost",
    isActive: true,
    sortOrder: 1,
  },
  {
    id: "cat-dairy",
    slug: "dairy-items",
    name: "Dairy Items",
    description: "Cheese, cream, butter, and more.",
    imageUrl: null,
    accentTone: "gold",
    isActive: true,
    sortOrder: 2,
  },
  {
    id: "cat-extra",
    slug: "extra-items",
    name: "Extra Items",
    description: "Small extras that complete the basket.",
    imageUrl: null,
    accentTone: "ink",
    isActive: true,
    sortOrder: 3,
  },
];

export const products: Product[] = [
  {
    id: "prd-fries",
    categoryId: "cat-frozen",
    categorySlug: "frozen-food",
    categoryName: "Frozen Food",
    slug: "signature-fries",
    name: "Signature Fries",
    shortDescription: "Crisp-cut golden fries with freezer-to-table speed.",
    description:
      "A premium cut built for even browning, clean seasoning, and reliable crunch across busy evenings.",
    price: 1450,
    compareAtPrice: 1650,
    unitLabel: "750g",
    badge: "Best Seller",
    stockStatus: "in_stock",
    isFeatured: true,
    isFrozen: true,
    accentTone: "frost",
    galleryUrls: [],
    createdAt: "2026-04-12T08:00:00.000Z",
  },
  {
    id: "prd-nuggets",
    categoryId: "cat-frozen",
    categorySlug: "frozen-food",
    categoryName: "Frozen Food",
    slug: "buttermilk-nuggets",
    name: "Buttermilk Nuggets",
    shortDescription: "Tender, crisp-edged bites with a soft dairy finish.",
    description:
      "An indulgent frozen line with premium crumb texture and a softer, richer interior.",
    price: 1850,
    compareAtPrice: 2100,
    unitLabel: "900g",
    badge: "Chef Pick",
    stockStatus: "low_stock",
    isFeatured: true,
    isFrozen: true,
    accentTone: "frost",
    galleryUrls: [],
    createdAt: "2026-04-14T09:15:00.000Z",
  },
  {
    id: "prd-cheddar",
    categoryId: "cat-dairy",
    categorySlug: "dairy-items",
    categoryName: "Dairy Items",
    slug: "aged-cheddar-block",
    name: "Aged Cheddar Block",
    shortDescription: "Deep savoury character for boards, burgers, and melts.",
    description:
      "A structured cheddar with bold colour, clean slicing, and premium everyday versatility.",
    price: 2250,
    compareAtPrice: null,
    unitLabel: "400g",
    badge: "Signature",
    stockStatus: "in_stock",
    isFeatured: true,
    isFrozen: false,
    accentTone: "gold",
    galleryUrls: [],
    createdAt: "2026-04-15T07:45:00.000Z",
  },
  {
    id: "prd-mozzarella",
    categoryId: "cat-dairy",
    categorySlug: "dairy-items",
    categoryName: "Dairy Items",
    slug: "pizza-mozzarella",
    name: "Pizza Mozzarella",
    shortDescription: "Stretchy, creamy, and balanced for clean blistering.",
    description:
      "A smooth mozzarella designed for rich melt coverage and a polished pizza finish.",
    price: 1950,
    compareAtPrice: 2250,
    unitLabel: "500g",
    badge: "Melt Hero",
    stockStatus: "in_stock",
    isFeatured: false,
    isFrozen: false,
    accentTone: "gold",
    galleryUrls: [],
    createdAt: "2026-04-10T11:20:00.000Z",
  },
  {
    id: "prd-truffle-mayo",
    categoryId: "cat-extra",
    categorySlug: "extra-items",
    categoryName: "Extra Items",
    slug: "truffle-mayo",
    name: "Truffle Mayo",
    shortDescription: "Luxury condiment energy for fries, sliders, and platters.",
    description:
      "A glossy finishing sauce built to elevate fast dinners with very little effort.",
    price: 1250,
    compareAtPrice: null,
    unitLabel: "250ml",
    badge: "Limited Batch",
    stockStatus: "in_stock",
    isFeatured: false,
    isFrozen: false,
    accentTone: "ink",
    galleryUrls: [],
    createdAt: "2026-04-09T13:00:00.000Z",
  },
  {
    id: "prd-brioche",
    categoryId: "cat-extra",
    categorySlug: "extra-items",
    categoryName: "Extra Items",
    slug: "butter-brioche-buns",
    name: "Butter Brioche Buns",
    shortDescription: "Soft structure, glossy tops, premium burger presentation.",
    description:
      "A visual upgrade for sliders and burgers with a plush crumb and buttery aroma.",
    price: 980,
    compareAtPrice: 1100,
    unitLabel: "6 pack",
    badge: "Bundle Ready",
    stockStatus: "out_of_stock",
    isFeatured: true,
    isFrozen: false,
    accentTone: "ink",
    galleryUrls: [],
    createdAt: "2026-04-16T06:30:00.000Z",
  },
];

export const deals: Deal[] = [
  {
    id: "deal-weekend-box",
    slug: "weekend-gathering-box",
    name: "Weekend Gathering Box",
    headline: "Frozen starters, dips, and cheese in one polished drop.",
    description:
      "An elegant basket for quick hosting with a strong visual mix of cold storage lines and dairy staples.",
    savingsLabel: "Save PKR 1,150",
    bannerImageUrl: null,
    discountType: "fixed",
    discountValue: 1150,
    startsAt: "2026-04-10T00:00:00.000Z",
    endsAt: "2026-04-28T23:59:59.000Z",
    status: "active",
    isActive: true,
    isFeatured: true,
    accentTone: "gold",
    includedItems: [
      {
        id: "deal-item-1",
        dealId: "deal-weekend-box",
        productId: "prd-fries",
        productSlug: "signature-fries",
        productName: "Signature Fries",
        quantity: 1,
        unitLabel: "750g",
        unitPrice: 1450,
        imageUrl: null,
      },
      {
        id: "deal-item-2",
        dealId: "deal-weekend-box",
        productId: "prd-cheddar",
        productSlug: "aged-cheddar-block",
        productName: "Aged Cheddar Block",
        quantity: 1,
        unitLabel: "400g",
        unitPrice: 2250,
        imageUrl: null,
      },
      {
        id: "deal-item-3",
        dealId: "deal-weekend-box",
        productId: "prd-truffle-mayo",
        productSlug: "truffle-mayo",
        productName: "Truffle Mayo",
        quantity: 1,
        unitLabel: "250ml",
        unitPrice: 1250,
        imageUrl: null,
      },
    ],
    originalTotal: 4950,
    dealPrice: 3800,
  },
  {
    id: "deal-pizza-night",
    slug: "pizza-night-ritual",
    name: "Pizza Night Ritual",
    headline: "Mozzarella, fries, sauces, and sides tuned for comfort.",
    description:
      "A family-style deal anchored by stretchy cheese and freezer-friendly add-ons.",
    savingsLabel: "Save PKR 850",
    bannerImageUrl: null,
    discountType: "fixed",
    discountValue: 850,
    startsAt: "2026-04-12T00:00:00.000Z",
    endsAt: "2026-04-24T23:59:59.000Z",
    status: "active",
    isActive: true,
    isFeatured: true,
    accentTone: "frost",
    includedItems: [
      {
        id: "deal-item-4",
        dealId: "deal-pizza-night",
        productId: "prd-mozzarella",
        productSlug: "pizza-mozzarella",
        productName: "Pizza Mozzarella",
        quantity: 2,
        unitLabel: "500g",
        unitPrice: 1950,
        imageUrl: null,
      },
      {
        id: "deal-item-5",
        dealId: "deal-pizza-night",
        productId: "prd-fries",
        productSlug: "signature-fries",
        productName: "Signature Fries",
        quantity: 1,
        unitLabel: "750g",
        unitPrice: 1450,
        imageUrl: null,
      },
      {
        id: "deal-item-6",
        dealId: "deal-pizza-night",
        productId: "prd-truffle-mayo",
        productSlug: "truffle-mayo",
        productName: "Truffle Mayo",
        quantity: 1,
        unitLabel: "250ml",
        unitPrice: 1250,
        imageUrl: null,
      },
    ],
    originalTotal: 6600,
    dealPrice: 5750,
  },
  {
    id: "deal-burger-lab",
    slug: "burger-lab-kit",
    name: "Burger Lab Kit",
    headline: "Brioche, nuggets, sauces, and layered dairy richness.",
    description:
      "A flexible kit for high-end casual dinners that still feels efficient to order.",
    savingsLabel: "Bundle Save PKR 920",
    bannerImageUrl: null,
    discountType: "bundle",
    discountValue: 920,
    startsAt: "2026-04-20T00:00:00.000Z",
    endsAt: "2026-05-02T23:59:59.000Z",
    status: "scheduled",
    isActive: true,
    isFeatured: false,
    accentTone: "ink",
    includedItems: [
      {
        id: "deal-item-7",
        dealId: "deal-burger-lab",
        productId: "prd-brioche",
        productSlug: "butter-brioche-buns",
        productName: "Butter Brioche Buns",
        quantity: 1,
        unitLabel: "6 pack",
        unitPrice: 980,
        imageUrl: null,
      },
      {
        id: "deal-item-8",
        dealId: "deal-burger-lab",
        productId: "prd-nuggets",
        productSlug: "buttermilk-nuggets",
        productName: "Buttermilk Nuggets",
        quantity: 1,
        unitLabel: "900g",
        unitPrice: 1850,
        imageUrl: null,
      },
      {
        id: "deal-item-9",
        dealId: "deal-burger-lab",
        productId: "prd-cheddar",
        productSlug: "aged-cheddar-block",
        productName: "Aged Cheddar Block",
        quantity: 1,
        unitLabel: "400g",
        unitPrice: 2250,
        imageUrl: null,
      },
    ],
    originalTotal: 5080,
    dealPrice: 4160,
  },
];

export const dealItems: DealItem[] = [
  {
    id: "deal-item-1",
    dealId: "deal-weekend-box",
    productId: "prd-fries",
    quantity: 1,
  },
  {
    id: "deal-item-2",
    dealId: "deal-weekend-box",
    productId: "prd-cheddar",
    quantity: 1,
  },
  {
    id: "deal-item-3",
    dealId: "deal-weekend-box",
    productId: "prd-truffle-mayo",
    quantity: 1,
  },
  {
    id: "deal-item-4",
    dealId: "deal-pizza-night",
    productId: "prd-mozzarella",
    quantity: 2,
  },
  {
    id: "deal-item-5",
    dealId: "deal-pizza-night",
    productId: "prd-fries",
    quantity: 1,
  },
  {
    id: "deal-item-6",
    dealId: "deal-pizza-night",
    productId: "prd-truffle-mayo",
    quantity: 1,
  },
  {
    id: "deal-item-7",
    dealId: "deal-burger-lab",
    productId: "prd-brioche",
    quantity: 1,
  },
  {
    id: "deal-item-8",
    dealId: "deal-burger-lab",
    productId: "prd-nuggets",
    quantity: 1,
  },
  {
    id: "deal-item-9",
    dealId: "deal-burger-lab",
    productId: "prd-cheddar",
    quantity: 1,
  },
];

export const deliveryZones: DeliveryZone[] = [
  {
    id: "zone-latifabad",
    slug: "latifabad",
    name: "Latifabad",
    description: "Fast-turn delivery for the core Hyderabad catchment.",
    deliveryCharge: 220,
    freeDeliveryMinimum: 5000,
    estimatedDeliveryTime: "30-45 mins",
    accentTone: "gold",
    isActive: true,
    sortOrder: 1,
    areas: [
      {
        id: "area-latifabad-unit-6",
        deliveryZoneId: "zone-latifabad",
        slug: "unit-6",
        name: "Unit 6",
        deliveryCharge: 220,
        isActive: true,
        sortOrder: 1,
      },
      {
        id: "area-latifabad-unit-7",
        deliveryZoneId: "zone-latifabad",
        slug: "unit-7",
        name: "Unit 7",
        deliveryCharge: 260,
        isActive: true,
        sortOrder: 2,
      },
      {
        id: "area-latifabad-autobahn-road",
        deliveryZoneId: "zone-latifabad",
        slug: "autobahn-road",
        name: "Autobahn Road",
        deliveryCharge: 300,
        isActive: true,
        sortOrder: 3,
      },
    ],
  },
  {
    id: "zone-qasimabad",
    slug: "qasimabad",
    name: "Qasimabad",
    description: "Balanced route timing with same-day cold-chain handling.",
    deliveryCharge: 320,
    freeDeliveryMinimum: 6500,
    estimatedDeliveryTime: "45-60 mins",
    accentTone: "frost",
    isActive: true,
    sortOrder: 2,
    areas: [
      {
        id: "area-qasimabad-phase-1",
        deliveryZoneId: "zone-qasimabad",
        slug: "phase-1",
        name: "Phase 1",
        deliveryCharge: 320,
        isActive: true,
        sortOrder: 1,
      },
      {
        id: "area-qasimabad-phase-2",
        deliveryZoneId: "zone-qasimabad",
        slug: "phase-2",
        name: "Phase 2",
        deliveryCharge: 360,
        isActive: true,
        sortOrder: 2,
      },
      {
        id: "area-qasimabad-phase-3",
        deliveryZoneId: "zone-qasimabad",
        slug: "phase-3",
        name: "Phase 3",
        deliveryCharge: 410,
        isActive: true,
        sortOrder: 3,
      },
    ],
  },
  {
    id: "zone-city-edge",
    slug: "city-edge",
    name: "City Edge",
    description: "Outer Hyderabad radius with extended route coordination.",
    deliveryCharge: 450,
    freeDeliveryMinimum: 8000,
    estimatedDeliveryTime: "60-90 mins",
    accentTone: "ink",
    isActive: true,
    sortOrder: 3,
    areas: [
      {
        id: "area-city-edge-ring-road",
        deliveryZoneId: "zone-city-edge",
        slug: "ring-road",
        name: "Ring Road",
        deliveryCharge: 450,
        isActive: true,
        sortOrder: 1,
      },
      {
        id: "area-city-edge-hosiery-market",
        deliveryZoneId: "zone-city-edge",
        slug: "hosiery-market",
        name: "Hosiery Market",
        deliveryCharge: 520,
        isActive: true,
        sortOrder: 2,
      },
      {
        id: "area-city-edge-bypass-corridor",
        deliveryZoneId: "zone-city-edge",
        slug: "bypass-corridor",
        name: "Bypass Corridor",
        deliveryCharge: 600,
        isActive: true,
        sortOrder: 3,
      },
    ],
  },
];

export const sampleCart: CartLine[] = [
  {
    id: "cart-1",
    itemType: "product",
    productId: "prd-cheddar",
    slug: "aged-cheddar-block",
    productName: "Aged Cheddar Block",
    quantity: 1,
    unitPrice: 2250,
    categoryName: "Dairy Items",
    categorySlug: "dairy-items",
    unitLabel: "400g",
    badge: "Signature",
  },
  {
    id: "cart-2",
    itemType: "product",
    productId: "prd-fries",
    slug: "signature-fries",
    productName: "Signature Fries",
    quantity: 2,
    unitPrice: 1450,
    compareAtPrice: 1650,
    categoryName: "Frozen Food",
    categorySlug: "frozen-food",
    unitLabel: "750g",
    badge: "Best Seller",
  },
];

export const dashboardMetrics: DashboardMetric[] = [
  {
    label: "Live SKUs",
    value: "48",
    hint: "Across frozen, dairy, and extras",
  },
  {
    label: "Orders Today",
    value: "19",
    hint: "Most opening through WhatsApp checkout",
  },
  {
    label: "Average Basket",
    value: "PKR 4.8k",
    hint: "Lifted by curated deal bundles",
  },
  {
    label: "Active Zones",
    value: "3",
    hint: "Delivery charge driven by database settings",
  },
];

export const recentOrders: Order[] = [
  {
    id: "ord-1",
    orderNumber: "HCS-4B18E211",
    customerName: "Ayesha Khan",
    phone: "03001234567",
    address: "House 15, Street 9, Qasimabad, Hyderabad",
    note: "Please call on arrival.",
    deliveryZoneId: "zone-qasimabad",
    deliveryZoneName: "Qasimabad",
    deliveryZoneAreaId: "area-qasimabad-phase-1",
    deliveryZoneAreaName: "Phase 1",
    deliveryCharge: 320,
    subtotal: 5150,
    total: 5470,
    status: "Confirmed",
    whatsappSent: true,
    createdAt: "2026-04-15T10:15:00.000Z",
    items: [
      {
        id: "order-item-1",
        orderId: "ord-1",
        productId: "prd-cheddar",
        productName: "Aged Cheddar Block",
        quantity: 1,
        unitPrice: 2250,
        lineTotal: 2250,
        itemType: "product",
        productSnapshot: {
          productId: "prd-cheddar",
          slug: "aged-cheddar-block",
          name: "Aged Cheddar Block",
          itemType: "product",
          quantity: 1,
          unitPrice: 2250,
          compareAtPrice: null,
          unitLabel: "400g",
          categoryName: "Dairy Items",
          categorySlug: "dairy-items",
          imageUrl: null,
          badge: "Signature",
        },
      },
      {
        id: "order-item-2",
        orderId: "ord-1",
        productId: "prd-nuggets",
        productName: "Buttermilk Nuggets",
        quantity: 1,
        unitPrice: 1850,
        lineTotal: 1850,
        itemType: "product",
        productSnapshot: {
          productId: "prd-nuggets",
          slug: "buttermilk-nuggets",
          name: "Buttermilk Nuggets",
          itemType: "product",
          quantity: 1,
          unitPrice: 1850,
          compareAtPrice: 2100,
          unitLabel: "900g",
          categoryName: "Frozen Food",
          categorySlug: "frozen-food",
          imageUrl: null,
          badge: "Chef Pick",
        },
      },
      {
        id: "order-item-3",
        orderId: "ord-1",
        productId: "prd-truffle-mayo",
        productName: "Truffle Mayo",
        quantity: 1,
        unitPrice: 1050,
        lineTotal: 1050,
        itemType: "product",
        productSnapshot: {
          productId: "prd-truffle-mayo",
          slug: "truffle-mayo",
          name: "Truffle Mayo",
          itemType: "product",
          quantity: 1,
          unitPrice: 1050,
          compareAtPrice: null,
          unitLabel: "250ml",
          categoryName: "Extra Items",
          categorySlug: "extra-items",
          imageUrl: null,
          badge: "Limited Batch",
        },
      },
    ],
  },
  {
    id: "ord-2",
    orderNumber: "HCS-88CD9F43",
    customerName: "Hamza Ali",
    phone: "03119876543",
    address: "Flat 6B, River View, Hyderabad",
    note: null,
    deliveryZoneId: "zone-latifabad",
    deliveryZoneName: "Latifabad",
    deliveryZoneAreaId: "area-latifabad-unit-6",
    deliveryZoneAreaName: "Unit 6",
    deliveryCharge: 220,
    subtotal: 3700,
    total: 3920,
    status: "Preparing",
    whatsappSent: false,
    createdAt: "2026-04-15T09:20:00.000Z",
    items: [
      {
        id: "order-item-4",
        orderId: "ord-2",
        productId: "prd-fries",
        productName: "Signature Fries",
        quantity: 2,
        unitPrice: 1450,
        lineTotal: 2900,
        itemType: "product",
        productSnapshot: {
          productId: "prd-fries",
          slug: "signature-fries",
          name: "Signature Fries",
          itemType: "product",
          quantity: 2,
          unitPrice: 1450,
          compareAtPrice: 1650,
          unitLabel: "750g",
          categoryName: "Frozen Food",
          categorySlug: "frozen-food",
          imageUrl: null,
          badge: "Best Seller",
        },
      },
      {
        id: "order-item-5",
        orderId: "ord-2",
        productId: "prd-brioche",
        productName: "Butter Brioche Buns",
        quantity: 1,
        unitPrice: 800,
        lineTotal: 800,
        itemType: "product",
        productSnapshot: {
          productId: "prd-brioche",
          slug: "butter-brioche-buns",
          name: "Butter Brioche Buns",
          itemType: "product",
          quantity: 1,
          unitPrice: 800,
          compareAtPrice: 1100,
          unitLabel: "6 pack",
          categoryName: "Extra Items",
          categorySlug: "extra-items",
          imageUrl: null,
          badge: "Bundle Ready",
        },
      },
    ],
  },
  {
    id: "ord-3",
    orderNumber: "HCS-13A6D770",
    customerName: "Sara Memon",
    phone: "03335671234",
    address: "Canal Road, Office delivery, Hyderabad",
    note: "Add extra ice pack if possible.",
    deliveryZoneId: "zone-city-edge",
    deliveryZoneName: "City Edge",
    deliveryZoneAreaId: "area-city-edge-ring-road",
    deliveryZoneAreaName: "Ring Road",
    deliveryCharge: 450,
    subtotal: 3800,
    total: 4250,
    status: "New",
    whatsappSent: true,
    createdAt: "2026-04-15T08:05:00.000Z",
    items: [
      {
        id: "order-item-6",
        orderId: "ord-3",
        productId: null,
        productName: "Weekend Gathering Box",
        quantity: 1,
        unitPrice: 3800,
        lineTotal: 3800,
        itemType: "deal",
        productSnapshot: {
          productId: null,
          slug: "weekend-gathering-box",
          name: "Weekend Gathering Box",
          itemType: "deal",
          quantity: 1,
          unitPrice: 3800,
          compareAtPrice: null,
          unitLabel: null,
          categoryName: null,
          categorySlug: null,
          imageUrl: null,
          badge: null,
          includedItems: [
            {
              id: "deal-item-1",
              dealId: "deal-weekend-box",
              productId: "prd-fries",
              productSlug: "signature-fries",
              productName: "Signature Fries",
              quantity: 1,
              unitLabel: "750g",
              unitPrice: 1450,
              imageUrl: null,
            },
            {
              id: "deal-item-2",
              dealId: "deal-weekend-box",
              productId: "prd-cheddar",
              productSlug: "aged-cheddar-block",
              productName: "Aged Cheddar Block",
              quantity: 1,
              unitLabel: "400g",
              unitPrice: 2250,
              imageUrl: null,
            },
            {
              id: "deal-item-3",
              dealId: "deal-weekend-box",
              productId: "prd-truffle-mayo",
              productSlug: "truffle-mayo",
              productName: "Truffle Mayo",
              quantity: 1,
              unitLabel: "250ml",
              unitPrice: 1250,
              imageUrl: null,
            },
          ],
        },
      },
    ],
  },
];

export const featuredProducts = products.filter((product) => product.isFeatured);
export const featuredDeals = deals.filter((deal) => deal.isFeatured);
